### ISSUE TITLE
SQL Search Extension Azure Data Studio Redirects to spawn.cc

### ISSUE THREAD

**Issue by NapalmCodes** [red-gate/foundry#56]
When I click install SQL Search in azure data studio it redirects to spawn.cc?
How do I install the plugin now for my new machine?

**Comment by carl33p** [comment]
Most likely an unintended redirect from https://www.redgatefoundry.com -> spawn.cc

**Comment by cjheppell** [comment]
Sorry about that! For context, https://spawn.cc is the website for another project we're working on in the Foundry at Redgate. But it seems we've ended up redirecting more than we intended.

We'll review this and see if we can reinstate the original download links.

In the meantime, you can download the extension by navigating directly to the download (which is where the URL www.redgatefoundry.com/download/sqlsearch was originally redirecting to):

- Azure Data Studio extension: https://foundrylabssqlsearch.blob.core.windows.net/sqlops-sql-search/Latest/Redgate%20Foundry%20-%20Sql%20Search%20Extension.vsix
- Azure Data Studio (Insiders) extension: https://foundrylabssqlsearch.blob.core.windows.net/sqlops-sql-search-insiders/Latest/Redgate%20Foundry%20-%20Sql%20Search%20Extension%20Insiders.vsix

**Comment by cjheppell** [comment]
Sorry about that.

For context, https://spawn.cc is another project we're working on at the Foundry at Redgate so this _was_ an intentional redirect, but clearly it's been applied too widely!

I've just reverted that change, so `www.redgatefoundry.com` should now resolve to the original website, and the download links for SQL Search should be available again.

Please let me know if this isn't the case, and I'll reopen the issue.

(You might need to clear your browser cache!)

**Comment by NapalmCodes** [comment]
Thanks @cjheppell !
